USE `finhub`;

CREATE TABLE IF NOT EXISTS `signals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `symbol` VARCHAR(64) NOT NULL,
  `especie` VARCHAR(128) DEFAULT NULL,
  `name` VARCHAR(191) DEFAULT NULL,
  `exchange` VARCHAR(64) DEFAULT NULL,
  `currency` CHAR(3) DEFAULT NULL,
  `as_of` DATETIME NOT NULL,
  `action` ENUM('BUY','HOLD','SELL') NOT NULL,
  `confidence` DECIMAL(5,4) DEFAULT NULL,
  `horizon_days` INT UNSIGNED NOT NULL DEFAULT 30,
  `signal_strength` DECIMAL(12,6) DEFAULT NULL,
  `price_last` DECIMAL(20,8) DEFAULT NULL,
  `entry_reference` DECIMAL(20,8) DEFAULT NULL,
  `exp_return_pct` DECIMAL(10,6) DEFAULT NULL,
  `exp_return_amt` DECIMAL(20,8) DEFAULT NULL,
  `range_p10_pct` DECIMAL(10,6) DEFAULT NULL,
  `range_p50_pct` DECIMAL(10,6) DEFAULT NULL,
  `range_p90_pct` DECIMAL(10,6) DEFAULT NULL,
  `range_p10_amt` DECIMAL(20,8) DEFAULT NULL,
  `range_p90_amt` DECIMAL(20,8) DEFAULT NULL,
  `volatility_atr` DECIMAL(18,8) DEFAULT NULL,
  `stop_price` DECIMAL(20,8) DEFAULT NULL,
  `take_price` DECIMAL(20,8) DEFAULT NULL,
  `stop_distance_pct` DECIMAL(10,6) DEFAULT NULL,
  `take_distance_pct` DECIMAL(10,6) DEFAULT NULL,
  `risk_reward` DECIMAL(10,6) DEFAULT NULL,
  `trend_state` ENUM('UP','DOWN','SIDE') DEFAULT NULL,
  `momentum_state` ENUM('BULL','BEAR','NEUTRAL') DEFAULT NULL,
  `regime` ENUM('HIGH_VOL','LOW_VOL','NEUTRAL') DEFAULT NULL,
  `rationale_short` VARCHAR(255) DEFAULT NULL,
  `rationale_tags` JSON DEFAULT NULL,
  `rationale_json` JSON DEFAULT NULL,
  `data_quality` ENUM('OK','STALE','MISSING','PARTIAL') DEFAULT 'OK',
  `data_points_used` INT UNSIGNED DEFAULT NULL,
  `costs_included` TINYINT(1) NOT NULL DEFAULT 0,
  `backtest_ref` VARCHAR(128) DEFAULT NULL,
  `series_json` JSON DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `signals_symbol_idx` (`symbol`, `as_of`),
  KEY `signals_action_idx` (`action`),
  KEY `signals_horizon_idx` (`horizon_days`),
  KEY `signals_especie_idx` (`especie`(32))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

